# Site settings
title: Amazon Product Review
description: 'A blog sharing Amazon popular products reviews'
keywords: 'Amazon, Reviews'
tagline: 'Product Review'
author:
  name: 'winwinsfu'
  email: 'winwinsfu@gmail.com'
  url: 'https://je-pense.github.io/product-review'

# Build settings
baseurl: # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

sass:
  sass_dir: _sass

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: '1.0'

# Options
custom_header: false
custom_nav_footer: false
reverse: false
